### ISSUE TITLE
Illegal parameter number in definition of \blx@defformat@d. \usebibmacro{name:last-first}{#1}{#4

### ISSUE THREAD

**Issue by frjonsen** [henningpohl/sigchi-alternative#1]
Format of \DeclareNameFormat was changed in BibLaTeX 3.3, meaning this project no longer compiles with the latest package versions.

See: https://github.com/plk/biblatex/issues/372

**Comment by henningpohl** [comment]
With ACM moving to new templates (see [http://www.acm.org/publications/proceedings-template](http://www.acm.org/publications/proceedings-template)), this version of the older template is pretty much bound for deprecation. But thanks for letting me know. I might spin off the biblatex style into a separate package. There have also been a bunch of changes to the bibliography style so this one right now does not reflect the current use anyway.
